---
- name: Install apt dependencies
  ansible.builtin.apt:
    cache_valid_time: 3600
    name: "{{ tailscale_dependencies }}"
    state: present

- name: Add Tailscale signing key
  become: true
  ansible.builtin.get_url:
    url: "{{ tailscale_signkey }}"
    dest: "{{ tailscale_keyring }}"
    mode: '0644'

- name: Add Tailscale apt repository
  ansible.builtin.apt_repository:
    repo: "{{ tailscale_repo }}"
    filename: "tailscale.list"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
