---
- name: Install yum dependencies
  ansible.builtin.yum:
    name: "{{ tailscale_dependencies }}"
    state: present

- name: Add Tailscale yum repository
  ansible.builtin.command: yum-config-manager --add-repo {{ tailscale_repo }}
  args:
    creates: /etc/yum.repos.d/tailscale.repo

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: true
